services:
  - docker:dind

variables:
  BUILD_COMMAND: ./gradlew

stages:
   - qa
   - build
   - release

run-tests:
   image: registry.gitlab.com/lievendoclo/hajdbc-spring-boot/alpine-java:8_jdk
   stage: qa
   script:
     - $BUILD_COMMAND test

build:
  image: registry.gitlab.com/lievendoclo/hajdbc-spring-boot/alpine-java:8_jdk
  stage: build
  script:
    - $BUILD_COMMAND clean assemble
  artifacts:
      paths:
          - build/libs/*.jar
      expire_in: 3 days
  except:
    - tags
